# Generated by Django 4.2.10 on 2024-02-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='modfiel_date',
            new_name='modfield_date',
        ),
        migrations.RenameField(
            model_name='historicalindicator',
            old_name='modfiel_date',
            new_name='modfield_date',
        ),
        migrations.RenameField(
            model_name='historicalmeasureunit',
            old_name='modfiel_date',
            new_name='modfield_date',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='modfiel_date',
            new_name='modfield_date',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='modfiel_date',
            new_name='modfield_date',
        ),
        migrations.RenameField(
            model_name='measureunit',
            old_name='modfiel_date',
            new_name='modfield_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='modfiel_date',
            new_name='modfield_date',
        ),
    ]
