# Generated by Django 4.2.10 on 2024-02-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_measure_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='modfield_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='historicalcategory',
            old_name='modfield_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='historicalindicator',
            old_name='modfield_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='historicalmeasureunit',
            old_name='modfield_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='modfield_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='modfield_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='measureunit',
            old_name='modfield_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='modfield_date',
            new_name='modified_date',
        ),
    ]
